### ISSUE TITLE
Testes Implementados

### ISSUE THREAD

**Issue by Gelmi** [LucJRibas/MC426-Eng-Software#32]

**Comment by eliasmarts** [comment]
Teste 1 - Teste da validação de data + horário do evento. Utilizamos classes de equivalência:
| Condição de entrada              | Válida  | Inválida |
|----------------------------------|---------|----------|
| Horário do evento medicação que se repete | Todas   | -  |
| Data + Horário do evento medicação que não se repete | >= agora | < agora  |
| Data + Horário do evento consulta        | >= agora | < agora  |

**Comment by eliasmarts** [comment]
Teste 3 - Teste das operações CRUD com a database do Room para a data Class Event

**Comment by eliasmarts** [comment]
Print dos testes funcionando na IDE Android Studio
![image](https://github.com/LucJRibas/MC426-Eng-Software/assets/87712292/6a0f8a30-3636-484a-a60f-5801d37d1bef)
![image](https://github.com/LucJRibas/MC426-Eng-Software/assets/87712292/41b3cf33-c499-4c39-9eea-5e211b5573a9)

**Comment by Gelmi** [comment]
https://github.com/LucJRibas/MC426-Eng-Software/pull/31
